#**Zajęcia nr 2**
## Podstawy języka Python - ciąg dalszy
Podczas zajęć omawiane oraz pokazane zostały kolejne zagadnienia dotyczące języka Python. Szczególną uwaga zwrócona była na to, że Python jest językiem obiektowym. Ponadto można było zapoznać się budową klasy. Na koniec należało, tak jak na Zajęciach nr 1 wykonać ćwiczenia podsumowujące zdobytą wiedzę. 

##**Przykłady**

---


####Zapoznanie się ze strukturami danych: lista, krotka oraz wektor oraz możliwością działania na nich

In [ ]:
import numpy as np

In [ ]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [ ]:
a_list+b_list
n_array+n_array

array([ 2,  4,  6,  8, 10])

In [ ]:
a_list[3]

4

In [ ]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [ ]:
k_krotka[4]

5

In [ ]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [ ]:
n_array = np.array(a_list) # wektor numpy

In [ ]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat'], dtype=object)

####Poznanie struktury o nazwie słownik - bardzo przydatnej w programowaniu liniowym

In [ ]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [ ]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [ ]:
studenci_slownik["Zosia"]

22

In [ ]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [ ]:
for elementy in studenci_slownik.items():
    print(elementy)

('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])


In [ ]:
for elementy in studenci_slownik.values():
    print(elementy)

3
5
22
[2, 21]


In [ ]:
studenci_slownik["Cuthulu"]= -1000000

In [ ]:
studenci_slownik

{'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], 'Cuthulu': -1000000}

In [ ]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [ ]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 'Igor', 1: 'Frankek', 2: 'Zosia', 3: 'Julia', 4: 'Cuthulu'}


####Wykonywanie operacji na zbiorach

In [ ]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [ ]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [ ]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [ ]:
1 in a
"Igor" in studenci_slownik

True

#### Zapoznanie się z definiowaniem własnych klas

In [ ]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [ ]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [ ]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [ ]:
pio_zajecia.ile_zajec

4

In [ ]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [ ]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [ ]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia.ile_mispow()

4

In [ ]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [ ]:
print(pio_zajecia.ile_zajec)

5


In [ ]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [ ]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [ ]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##**Zadania do rozwiązania**


---


####Challenge 1

Zadanie sprawdzające polegało na stworzeniu typu `NumerTelefonu`, który

- przy tworzeniu sprawdza czy podany numer jest właściwy (polski); jeśli nie, wypisuje na ekranie "Error":
  - przyjęto, że numer jest prawidłowy (polski), jeżeli pierwsze dwie cyfry to `48`, a długość numeru to 9 cyfr. Jeżeli numer nie spełniał wymagań, na ekran wypisywano słowo `Error`.
 
- gdy należy wypisać "numer" na ekran, wypisuje po kolei słownie cyfry np. "jeden, pięć, siedem, zero":
  - stworzono listę zawierającą wszystkie cyfry w kolejności zapisane słownie. Następnie wybierano po kolei cyfry numeru i odczytywano słowo z listy na pozycji równej cyfrze zapisanej liczbowo. Ostatecznie wszystkie wyczytane cyfry sklejano ze sobą i wypisywano
 
- gdy wywoływana jest właściwość "wojewodzwtwo", podaje nazwę województwa. Jeżeli numer nie spełnia wymagań bycia numerem z konkretnego województwa, wypisuje że to numer komórkowy:
  - stworzono listę nazw miast wojewódzkich i poczatków numerów im odpowiadających. Jeżeli 3 i 4 cyfra numeru były takie same jak początki numeru tóregokolwiek z miast wojewódzkich, ustawiano zmienną `znaleziono_miasto` na 1 i wypisywano nazwę miasta wojewódzkiego. W przeciwnym razie wypisywano słowo "Komórkowy".
 
 

In [ ]:
class NumerTelefonu():
    
    def __init__(self, num):
        self.numer = num
        if (self.numer[0]+self.numer[1] == "48") and len(self.numer) == 9:
            print("Prawidlowy numer")
        else:
            print("Error")
    
    @property
    def wojewodztwo(self):
        znaleziono_miasto = 0
        lista_miasto_numer = [["Białystok", "85"], ["Bydgoszcz", "52"], ["Gdańsk", "58"], ["Gorzów Wielkopolski", "95"], ["Katowice", "32"], ["Kielce", "42"], ["Kraków", "12"],["Lublin", "81"], ["Łódź", "42"],["Olsztyn", "89"], ["Opole", "77"], ["Poznań", "61"]]
        for i in range(len(lista_miasto_numer)):
            if(self.numer[2]+self.numer[3] == lista_miasto_numer[i][1]):
                znaleziono_miasto = 1
                print(lista_miasto_numer[i][0])
        if(znaleziono_miasto == 0):
            print("Komorkowy")


    
    def __repr__(self):
        lista_pisemna = ["zero", "jeden", "dwa", "trzy", "cztery", "pięć", "sześć", "siedem", "osiem", "dziewięć" ]
        lista_nowa = ""
        for i in range(len(self.numer)):
            lista_nowa = lista_nowa + " " + lista_pisemna[int(self.numer[i])]
        return lista_nowa
        
        

Sprawdzenie działania stworzonej klasy

In [ ]:
numer = NumerTelefonu("489508880")

Prawidlowy numer


In [ ]:
numer.wojewodztwo

Gorzów Wielkopolski


In [ ]:
print(numer)

 cztery osiem dziewięć pięć zero osiem osiem osiem zero


In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć



numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

SyntaxError: invalid syntax (<ipython-input-156-46f967ae0f3d>, line 6)